### ISSUE TITLE
SUBMISSION OF TASK AND INVITATION FOR REVIEW

### ISSUE THREAD

**Issue by Nurmalee** [Nurmalee/github-pages-my-users-app-react#1]
Name: **Lawal Nurudeen Tobiloba**
Email: **lawalnurudeenfocus@gmail.com**

_This is an invitation for review to @bondz @dreplica and @markeu. Pls check README file for app usage details. Thanks as I expect your esteemed responses._

**Comment by bondz** [comment]
Put a link to your CI with a badge at the top of your Readme as specified in the assessment document.

**Comment by Nurmalee** [comment]
I will try to do that considering **this is my first time trying to test a react app or any app test whatsoever**. I am currently searching for procedures and possibilities. I will only hope I can get it done before expiration of deadline.

In the mean time, I want to believe whatever I have done may be enough for assessment to begin with. If that isn't the case, I hope to get notified as soon as possible. Thanks and good job @bondz

**Comment by bondz** [comment]
Not having tests does not disqualify you. However, its best practise to have tests for features you implement. Look at [Testing Library](https://testing-library.com/), it has tools for testing [React](https://testing-library.com/docs/react-testing-library/intro) and it comes bundled with Create React App.

**Comment by Nurmalee** [comment]
Very well then.. I'm currently working on it..
